version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/src/ClientApp"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 30
    target-branch: "main"
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 30
    target-branch: "main"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 30
    target-branch: "main"
