name: 🔨 CI Backend

on:
  push:
    paths-ignore:
      - "src/ClientApp/**"

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 📘 Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x.x

      - name: 🔄 Restore dependencies
        run: dotnet restore

      - name: 🔨 Build Project
        run: dotnet build --no-restore

      - name: 🧪 Test Project
        run: dotnet test --no-build --verbosity normal

      - name: 🔎 SonarCloud Scan
        uses: highbyte/sonarscan-dotnet@v2.3.2
        with:
          sonarProjectKey: thejaviertc_tfg_backend
          sonarProjectName: thejaviertc_tfg_backend
          sonarOrganization: thejaviertc
          sonarBeginArguments: /d:sonar.exclusions="ClientApp/**" -d:sonar.qualitygate.wait=true
          dotnetDisableTests: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_BACKEND }}
